### ISSUE TITLE
Build failures in Ember 4+ due to named outlet usage

### ISSUE THREAD

**Issue by rwjblue** [ember-animation/liquid-fire#668]
Ember 4+ errors on the following line:

https://github.com/ember-animation/liquid-fire/blob/54d4de34703395bee4e349585fc09fe95870ffe2/addon/templates/components/liquid-outlet.hbs#L19

With this error:

```
Error: Assertion Failed: Named outlets were removed in Ember 4.0. See deprecations.emberjs.com/v3.x#toc_route-render-template for guidance on alternative APIs for named outlet use cases. ('liquid-fire/templates/components/liquid-outlet.hbs' @ L19:C6) 
    at assert (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:1582:15)
    at MustacheStatement (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:17431:52)
    at visitNode (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10180:16)
    at visitArray (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10274:20)
    at visitKey (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10250:7)
    at visitNode (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10202:9)
    at visitKey (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10253:20)
    at visitNode (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10202:9)
    at visitArray (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10274:20)
    at visitKey (/home/runner/work/ember-collapsible-panel/ember-collapsible-panel/node_modules/ember-source/dist/ember-template-compiler.js:10250:7)
```

**Comment by rwjblue** [comment]
It seems that https://github.com/ember-animation/liquid-fire/pull/665 and https://github.com/ember-animation/liquid-fire/pull/667 were specifically trying to fix this. 

🤦‍♂️  I wasn't using latest, I was using `^0.32.0`.
